name: Super-Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: DEBUG

          # Linter configurations
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true  # Only validate changed files on PRs

          # Enable linting
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_MARKDOWN_PRETTIER: true

          # Enable auto-formatting
          FIX_PYTHON_RUFF: true
          FIX_MARKDOWN_PRETTIER: true

      - name: Commit and push linting fixes
        if: github.event_name == 'pull_request' && github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Auto-Format code with Super-Linter"
          branch: ${{ github.head_ref || github.ref_name }} # Pushes to the branch that triggered the workflow
          commit_user_name: "Github Actions (Super-Linter)"
          commit_user_email: "actions@github.com"
          commit_author: "Github Actions (Super-Linter) <actions@github.com>"
